# This file was generated by GoReleaser. DO NOT EDIT.
cask "teams-cli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "24bbc84f5d5d730dad6e9de005750b4485dfe121038fabf7f53b19dd3df22481"
      url "https://github.com/aeswibon/teams-cli/releases/download/v#{version}/teams-cli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/aeswibon/teams-cli/"
    end
    on_arm do
      sha256 "dc6795adaac86e29f0334da74ca48c33ef3e02e675464b208cdc22483ebe251f"
      url "https://github.com/aeswibon/teams-cli/releases/download/v#{version}/teams-cli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/aeswibon/teams-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "085f85e89860482ca2841a9f063b937cb1083e73518194ff224d53bc0f46fbe5"
      url "https://github.com/aeswibon/teams-cli/releases/download/v#{version}/teams-cli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/aeswibon/teams-cli/"
    end
    on_arm do
      sha256 "d553e21c9bbd9bbd9f5f8c8073524e209dc27420e540ebe5c05525d6f4c85936"
      url "https://github.com/aeswibon/teams-cli/releases/download/v#{version}/teams-cli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/aeswibon/teams-cli/"
    end
  end

  name "teams-cli"
  desc "CLI for Microsoft Teams chats and messages via Microsoft Graph API"
  homepage "https://github.com/aeswibon/teams-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "teams-cli"

  # No zap stanza required

  caveats <<~EOS
    Run `teams-cli init` to configure authentication before first use.
    See https://github.com/aeswibon/teams-cli for setup instructions.
  EOS
end
